# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('objetivo', models.CharField(max_length=40)),
                ('iphost', models.GenericIPAddressField()),
                ('mascara', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('mac', models.CharField(max_length=40)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.DecimalField(decimal_places=12, max_digits=14)),
                ('detalle_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DetalleConsulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Estado'),
        ),
    ]
