# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado')], default='Cerrado', max_length=40),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('I', 'Iniciada'), ('C', 'Cancelada'), ('T', 'Terminada')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
