# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180703_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(blank=True, default='16:45:45'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mascara',
            field=models.CharField(default='32', max_length=40),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='objetivo',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='detalleconsulta',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='detalleconsulta',
            name='hora',
            field=models.TimeField(default='16:45:45'),
        ),
    ]
